apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-app-hpa
  namespace: node-app-namespace
spec:
  maxReplicas: 5 
  minReplicas: 1 
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: node-app
  targetCPUUtilizationPercentage: 30

